<h1><font color=#EB7A77> 2.1 DataManipulation </h1>
    
<font color=#BF6766> 2.1 DataManipulation
    
<font color=#CB4042> 2.1 DataManipulation
    
<font color=#AB3B3A> 2.1 DataManipulation
    
<font color=#91B493> 2.1 DataManipulation
       
<font color=#86A697> 2.1 DataManipulation

<h1><font color=#CB4042> 2.1 DataManipulation </h1>

In [2]:
import numpy as np
import torch

In [3]:
# !! func is arange but not arrange!!
nd = np.arange(12, dtype=np.float64)
print(nd)
nd.shape

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


(12,)

In [4]:
# !! func is arange but not arrange!!
ts = torch.arange(12, dtype=torch.float64)
print(ts)
ts.shape

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       dtype=torch.float64)


torch.Size([12])

In [5]:
print(nd.size)
# notice: size in torch is a func but not a attribute
print(ts.size())

12
torch.Size([12])


In [6]:
nd2 = nd.reshape([3,4])
nd2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [7]:
ts2 = ts.reshape([4,3])
ts2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [8]:
ts

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       dtype=torch.float64)

In [9]:
zero_arr = np.zeros(5)
zero_ts = torch.zeros(5)
print(zero_arr)
print(zero_ts)

[0. 0. 0. 0. 0.]
tensor([0., 0., 0., 0., 0.])


In [10]:
one_arr = np.ones(5)
one_ts = torch.ones([2,3])
print(one_arr)
print(one_ts)

[1. 1. 1. 1. 1.]
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [11]:
# rand returns the random value btw 0 & 1,
# randn returns normal distribution
# random returns random float number
# randint returns random integer
rand_arr = np.random.randn(1,5)
# randomly sampled in a normal distribution with zero mean and unit variance.
rand_ts = torch.randn(1,5)
print(rand_arr)
print(rand_ts)
rand_arr.shape
rand_ts.shape

[[-0.25032576 -0.59776585 -0.56553926  1.08403899  0.3546074 ]]
tensor([[ 0.0140, -0.5990,  1.1935, -0.1492, -0.2563]])


torch.Size([1, 5])

## <font color=#EB7A77> create tensor by giving its shape

In [12]:
torch.Tensor(2,3)

tensor([[ 0.0000e+00, -0.0000e+00, -4.2347e-19],
        [ 8.5920e+09,  5.6052e-45, -0.0000e+00]])

In [13]:
torch.FloatTensor(4,5)

tensor([[8.2354e+23, 1.6457e+19, 3.0478e+32, 6.2618e+22, 4.7428e+30],
        [2.7947e+20, 3.0344e+32, 7.7783e+31, 6.2608e+22, 4.7428e+30],
        [1.1096e+27, 2.7518e+12, 7.5338e+28, 1.8037e+28, 6.7120e+22],
        [1.4226e-13, 6.2608e+22, 4.7428e+30, 3.5833e-14, 2.7947e+20]])

In [14]:
torch.empty(1,3)

tensor([[ 0.0000e+00, -0.0000e+00, -4.7528e-19]])

## <font color=#EB7A77> convert numpy and tensor

In [15]:
nd

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [16]:
ts

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       dtype=torch.float64)

In [17]:
convert = torch.from_numpy(nd.reshape(3,4))
convert

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

### <font color=#86A697> torch.Tensor() is a class in Python，which is another name of torch.FloatTensor()
### <font color=#86A697> while torch.tensor()is a func in Python，which is torch.tensor(data, dtype=None, device=None, requires_grad=False)

In [18]:
convert2 = torch.Tensor(np.arange(12).reshape(3,4))
convert2

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [19]:
convert3 = torch.tensor(np.arange(12).reshape(3,4), dtype=torch.float64)
convert3

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

In [20]:
convert4 = torch.tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.], dtype=torch.float64)
convert4

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       dtype=torch.float64)

In [21]:
ndarr = np.array([[1,2,3], [4,5,6]])
ndarr

array([[1, 2, 3],
       [4, 5, 6]])

# <font color=#CB4042>Operations (elementwise)

In [22]:
x = np.array([1,2,4,8])
y = np.array([2,2,2,2])

print('x-y', x-y)
print('x+y', x+y)
print('x*y', x*y)
print('x/y', x/y)
print('x**y', x**y)

x-y [-1  0  2  6]
x+y [ 3  4  6 10]
x*y [ 2  4  8 16]
x/y [0.5 1.  2.  4. ]
x**y [ 1  4 16 64]


In [23]:
x_t = torch.Tensor([1,2,4,8])
y_t = torch.ones_like(x_t) *2

print('x-y', x_t-y_t)
print('x+y', x_t+y_t)
print('x*y', x_t*y_t)
print('x/y', x_t/y_t)
print('x**y', x_t**y_t)

x-y tensor([-1.,  0.,  2.,  6.])
x+y tensor([ 3.,  4.,  6., 10.])
x*y tensor([ 2.,  4.,  8., 16.])
x/y tensor([0.5000, 1.0000, 2.0000, 4.0000])
x**y tensor([ 1.,  4., 16., 64.])


In [24]:
np.exp(x)

array([2.71828183e+00, 7.38905610e+00, 5.45981500e+01, 2.98095799e+03])

In [25]:
torch.exp(x_t)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

# <font color=#CB4042>Operations (linear algebra)

In [26]:
np.dot(x,y)

30

In [27]:
torch.dot(x_t, y_t)

tensor(30.)

In [38]:
m = np.random.randn(2,4)
m2 = np.random.randn(4,3)
m

array([[-0.66905144,  1.38972269, -0.39215837,  0.62687104],
       [-0.46798133, -0.72242962, -0.69936012, -0.57583807]])

In [40]:
np.dot(x, m2)

array([ 2.87912081, -4.41946759,  5.35858843])

In [41]:
m_t = torch.Tensor(m)
m2_t = torch.Tensor(m2)
m_t

tensor([[-0.6691,  1.3897, -0.3922,  0.6269],
        [-0.4680, -0.7224, -0.6994, -0.5758]])

In [70]:
torch.dot(x_t, m_t)

RuntimeError: 1D tensors expected, got 1D, 2D tensors at ../aten/src/TH/generic/THTensorEvenMoreMath.cpp:83

In [50]:
print(np.dot(m,m2))
print(m_t.shape)
print(m2_t.shape)
# torch.dot() treats both a and b as 1D vectors (irrespective of their original shape) and computes their inner product.
print(torch.(m_t*m2_t))

[[-1.26655675  0.59277489 -1.33672875]
 [-0.42345155  0.2675763   0.09335371]]
torch.Size([2, 4])
torch.Size([4, 3])


RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

In [61]:
print(x.shape)
print(y.shape)
print(np.concatenate([x,y], axis=0))
print(np.concatenate([x.reshape(2,2),y.reshape(2,2)], axis=1))
# y.reshape(2,2)

(4,)
(4,)
[1 2 4 8 2 2 2 2]
[[1 2 2 2]
 [4 8 2 2]]


In [62]:
print(x_t.shape)
print(y_t.shape)
print(torch.cat([x_t,y_t], axis=0))
print(torch.cat([x_t.reshape(2,2),y_t.reshape(2,2)], axis=1))

torch.Size([4])
torch.Size([4])
tensor([1., 2., 4., 8., 2., 2., 2., 2.])
tensor([[1., 2., 2., 2.],
        [4., 8., 2., 2.]])


In [63]:
x == y

array([False,  True, False, False])

In [65]:
x.sum()
x_t.sum()

tensor(15.)

In [68]:
x_t.norm().item()

9.219544410705566

# <font color=#CB4042>Broadcast Mechanism

In [82]:
a = np.arange(3).reshape(3,1)
b = np.arange(2).reshape(1,2)
print(a)
print(b)
a_t = torch.Tensor(a)
b_t = torch.Tensor(b)

[[0]
 [1]
 [2]]
[[0 1]]


In [83]:
print(a+b)
print(a_t+b_t)

[[0 1]
 [1 2]
 [2 3]]
tensor([[0., 1.],
        [1., 2.],
        [2., 3.]])


In [84]:
a*b
print(a_t*b_t)

tensor([[0., 0.],
        [0., 1.],
        [0., 2.]])


In [81]:
np.dot(a,b)

array([[0, 0],
       [0, 1],
       [0, 2]])

# <font color=#CB4042>Indexing and Slicing

In [85]:
print(x[0])
print(x_t[0])
print(m[:, :2])
print(m_t[:1, 2])

1
tensor(1.)
[[-0.66905144  1.38972269]
 [-0.46798133 -0.72242962]]
tensor([-0.3922])


In [86]:
x_t[0] = 2
print(x_t)

tensor([2., 2., 4., 8.])


In [88]:
m_t[:, :2] = 12
m_t

tensor([[12.0000, 12.0000, -0.3922,  0.6269],
        [12.0000, 12.0000, -0.6994, -0.5758]])

# <font color=#CB4042>Saving Memory

In [89]:
before = id(x_t)
x = x + y
before == id(x)

False

### <font color=#86A697> simple assignment can waste memory, we want to perform these updates *in place*.
    
    
    

In [91]:
x_t = torch.Tensor([1,2,4,8])
y_t = torch.ones_like(x_t) *2

before = id(x_t)
x_t[:] = x_t + y_t
before == id(x_t)

#  or 
before = id(x_t)
x_t += y_t
before == id(x_t)

True

# <font color=#CB4042>Conversion for tensor and ndarray

In [95]:
print(type(x))
print(type(torch.tensor(x)))
print(type(torch.Tensor(x)))
print(type(torch.from_numpy(x)))
print(type(x_t.numpy()))
print(type(np.array(x_t)))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


# <font color=#CB4042>Exercises

In [99]:
print(x)
print(y)
print(x>y)

[ 3  4  6 10]
[2 2 2 2]
[ True  True  True  True]


In [112]:
a = torch.arange(18).reshape(2,3,3)
b = torch.arange(9).reshape(1,3,3)
print(a)
print(b)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])
tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]])


In [113]:
a+b

tensor([[[ 0,  2,  4],
         [ 6,  8, 10],
         [12, 14, 16]],

        [[ 9, 11, 13],
         [15, 17, 19],
         [21, 23, 25]]])