## Scalar

In [1]:
import torch

In [2]:
x = torch.tensor(3,dtype=torch.float64)
x

tensor(3., dtype=torch.float64)

In [3]:
y = torch.Tensor([2])
y

tensor([2.])

In [4]:
print(x+y, x-y, x*y, x/y, x**y)

tensor([5.]) tensor([1.]) tensor([6.]) tensor([1.5000]) tensor([9.])


## Vectors

In [5]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [6]:
x[3]

tensor(3)

In [7]:
x.shape

torch.Size([4])

In [8]:
len(x)

4

In [9]:
x.size()

torch.Size([4])

## Matrices

In [65]:
x = torch.Tensor(2,3)
x

tensor([[ 0.0000e+00, -1.0842e-19,  0.0000e+00],
        [-1.0842e-19,  1.1210e-44,  0.0000e+00]])

In [42]:
y = torch.randn(2,3)
y

tensor([[0.4249, 1.6100, 0.2539],
        [0.9303, 0.5031, 0.5099]])

In [43]:
z = torch.ones(2,3)
z

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [67]:
x.T, x.t()

(tensor([[ 0.0000e+00, -1.0842e-19],
         [-1.0842e-19,  1.1210e-44],
         [ 0.0000e+00,  0.0000e+00]]),
 tensor([[ 0.0000e+00, -1.0842e-19],
         [-1.0842e-19,  1.1210e-44],
         [ 0.0000e+00,  0.0000e+00]]))

## Tensor operation

 ### 一、torch.mul()
 torch.mul() 支持广播操作，torch.mul(input, value, out=None)

 用标量值 value 乘以输入 input 的每个元素，并返回一个新的结果张量。 out = tensor ∗ value
 
 参数：
 - input (Tensor) – 输入张量
 - value (Number) – 乘到每个元素的数
 - out (Tensor, optional) – 输出张量
 
### 二、torch.mm()
 torch.mm()不支持广播（broadcast），torch.mm(mat1, mat2, out=None) → Tensor
 
 对矩阵mat1和mat2进行相乘。 如果mat1 -> n×m，mat2 -> m×p，out -> n×p。
 
### 三、torch.mv()
 注意，torch.mv()不支持广播（broadcast）, torch.mv(mat, vec, out=None) → Tensor
 
 对矩阵mat和向量vec进行相乘。 如果mat -> n×m，vec ->m元1维张量，out -> n元1维张量。

 
### 四、torch.dot()
 注意，torch.dot()不支持广播（broadcast）, torch.dot(tensor1, tensor2) → Tensor

 计算两个张量的点乘(内乘),两个张量都为1-D 向量
 
 
### 五、torch.matmul()
 注意：torch.matmul() 支持广播, torch.matmul(input, other, out=None) → Tensor

 两个张量的矩阵乘积
 
 计算结果取决于张量的维度：
 
 1）如果两个张量都是 1 维，返回结果为 the dot product (scalar) 【点乘（标量）】

 2）如果两个张量都是 2 维，返回结果为  the matrix-matrix product (矩阵乘积)

 3）如果第一个参数是 1 维，第二个参数是 2 维，为了矩阵乘法的目的，在第一维上加 1（达到扩充维度的目的），
 
   矩阵计算完成之后，第一维加上的 1 将会被删掉。

 4）如果第一个参数是 2 维，第二个参数是 1 维，返回结果为 the matrix-vector product (矩阵向量乘积)

 5）如果两个参数至少是 1 维且至少一个参数为 N 维（其中N> 2），则返回 batched matrix multiply (批处理矩阵乘法)
 
   如果第一个参数是 1 维，则在其维数之前添加 1，以实现批量矩阵乘法并在计算之后删除 1。
   
   如果第二个参数是 1 维，则在其维数之前添加 1，以实现批量矩阵乘法并在计算之后删除 1。
   
   非矩阵（即批处理）尺寸被广播（因此必须是可广播的）。
   
   例如，如果 input 的张量是  j×1×n×m ，
   
            other 的张量是  k×m×p，
            
            out 的张量将会是 j×k×n×p
 

In [48]:
X = torch.Tensor(2,3)
Z = torch.ones(2,3)
Y = torch.randn(2,3)
# elementwise operation
X+Y
# elementwise hadamard product
X*Z

tensor([[ 0.0000e+00, -1.0842e-19, -2.1438e+05],
        [-2.5250e-29,  9.8091e-45,  0.0000e+00]])

In [49]:
# add or multiply by a scalar
print(X+2)
print(X*2)
torch.mul(X,2)

tensor([[ 2.0000e+00,  2.0000e+00, -2.1438e+05],
        [ 2.0000e+00,  2.0000e+00,  2.0000e+00]])
tensor([[ 0.0000e+00, -2.1684e-19, -4.2877e+05],
        [-5.0499e-29,  1.9618e-44,  0.0000e+00]])


tensor([[ 0.0000e+00, -2.1684e-19, -4.2877e+05],
        [-5.0499e-29,  1.9618e-44,  0.0000e+00]])

### Reduction Operation

In [50]:
# sum
A = torch.arange(12).reshape(3,4)
A = A.float()
A.sum(), A.sum(axis=0)

(tensor(66.), tensor([12., 15., 18., 21.]))

In [51]:
A.mean(), A.mean(axis=1)

(tensor(5.5000), tensor([1.5000, 5.5000, 9.5000]))

### None-Reduction Operation

In [52]:
A.sum(axis=0, keepdims=True), A.mean(axis=1, keepdims=True)

(tensor([[12., 15., 18., 21.]]),
 tensor([[1.5000],
         [5.5000],
         [9.5000]]))

In [53]:
col_sum = A.sum(axis=0, keepdims=True)
A / col_sum

tensor([[0.0000, 0.0667, 0.1111, 0.1429],
        [0.3333, 0.3333, 0.3333, 0.3333],
        [0.6667, 0.6000, 0.5556, 0.5238]])

In [54]:
# cumulative sum: sum row1 to row2, row2 to row3
A.cumsum(axis=0), A.cumsum(axis=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  6.,  8., 10.],
         [12., 15., 18., 21.]]),
 tensor([[ 0.,  1.,  3.,  6.],
         [ 4.,  9., 15., 22.],
         [ 8., 17., 27., 38.]]))

###  Dot Product

In [56]:
# Vector dot product
x = torch.arange(4)
y = torch.ones(4)
y = y.long()
# equal to the sum of elementwise multi
x*y, sum(x*y), torch.dot(x,y)

(tensor([0, 1, 2, 3]), tensor(6), tensor(6))

### Matrix-Vector Product

In [60]:
x = torch.arange(5).float()
A = torch.randn(3,5)
torch.mv(A, x)

tensor([5.7562, 0.1421, 2.2818])

### Matrix-Matrix Multiplication

In [62]:
X = torch.ones(3,4)
Y = torch.randn(4,2)
torch.mm(X,Y)

tensor([[4.5237, 1.1856],
        [4.5237, 1.1856],
        [4.5237, 1.1856]])

In [63]:
torch.Tensor(3,4)b

tensor([[ 0.0000e+00, -1.0842e-19,  0.0000e+00, -1.0842e-19],
        [ 9.8091e-45,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

## Norm

In [74]:
x = torch.Tensor([1, -1, 2, 3])
# l2-norm
x, torch.norm(x)

(tensor([ 1., -1.,  2.,  3.]), tensor(3.8730))

In [79]:
# l1-norm
abs(x), abs(x).sum(), torch.sum(torch.abs(x))

(tensor([1., 1., 2., 3.]), tensor(7.), tensor(7.))

In [78]:
A = torch.randn(3,4, dtype=torch.float)
# l2-norm for matrix, or Frobenius norm
A, torch.norm(A)

(tensor([[-1.6204, -1.2571,  0.8883,  0.8274],
         [ 1.2613,  0.2961, -0.8088,  0.9048],
         [ 1.0167,  0.4229, -2.6556,  0.3054]]),
 tensor(4.1459))

## Exercises

In [80]:
A.t().t() == A

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [85]:
X = torch.Tensor(2,3,4)
X.shape, len(X)

(torch.Size([2, 3, 4]), 2)

In [93]:
A.sum(axis=1), A.shape, A.sum(axis=1).shape, A.sum(axis=0).shape

(tensor([-1.1619,  1.6534, -0.9106]),
 torch.Size([3, 4]),
 torch.Size([3]),
 torch.Size([4]))

In [90]:
A / A.sum(axis=0)

tensor([[-2.4641,  2.3363, -0.3448,  0.4061],
        [ 1.9181, -0.5503,  0.3140,  0.4441],
        [ 1.5461, -0.7860,  1.0308,  0.1499]])

In [91]:
A / A.sum(axis=1)

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

In [97]:
B = torch.ones(2,3)
x = torch.arange(2)
y = torch.arange(3)
B, B/y

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[   inf, 1.0000, 0.5000],
         [   inf, 1.0000, 0.5000]]))

In [99]:
X.shape, X.sum(axis=0).shape, X.sum(axis=1).shape, X.sum(axis=2).shape

(torch.Size([2, 3, 4]),
 torch.Size([3, 4]),
 torch.Size([2, 4]),
 torch.Size([2, 3]))

In [105]:
A = torch.arange(12, dtype=torch.float).reshape(2,3,2)
A, torch.norm(A)

(tensor([[[ 0.,  1.],
          [ 2.,  3.],
          [ 4.,  5.]],
 
         [[ 6.,  7.],
          [ 8.,  9.],
          [10., 11.]]]),
 tensor(22.4944))

In [108]:
import numpy as np
sum = 0
for i in range(12):
    sum += i ** 2
np.sqrt(sum)

22.494443758403985